version: '3.3'

services:
  golang:
    build:
      context: golang-app\.

  redis:
    image: redis:7.4.1
    restart: always
    ports:
      - "6379:6379"
    volumes:
#      - /path/to/local/d–∞ta:/root/redis
      - /redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16